;; init.el --- -*- lexical-binding: t no-byte-compile: t -*-
(add-to-list 'load-path "~/.emacs.d/lisp")

(require 'init-ui)
(require 'init-spacious-padding)
(require 'init-doom-modeline)
(require 'init-themes)
(require 'init-flycheck)
(require 'init-corfu)
(require 'init-cape)
(require 'init-backup-files)
(require 'init-qol)
(require 'init-dashboard)
(require 'init-dired)
(require 'init-consult)
(require 'init-projectile)
(require 'init-ace-window)
(require 'init-savehist)
(require 'init-marginalia)
(require 'init-emacs)
(require 'init-vertico)
(require 'init-orderless)
(require 'init-direnv)
(require 'init-nix-mode)
(require 'init-magit)
(require 'init-avy)
(require 'init-org-roam)
(require 'init-org)
(require 'init-yas)
(require 'init-salt-mode)
(require 'init-eglot)
(require 'init-custom-fun)
(require 'init-embark)

(require 'tuxikus-eat)

;; init.el ends here
