;; init.el --- -*- lexical-binding: t no-byte-compile: t -*-
(add-to-list 'load-path "~/.emacs.d/lisp")

(require 'config-ui)
(require 'config-spacious-padding)
(require 'config-doom-modeline)
(require 'config-themes)
(require 'config-backup-files)
(require 'config-qol)
(require 'config-dashboard)
(require 'config-dired)
(require 'config-consult)
(require 'config-projectile)
(require 'config-ace-window)
(require 'config-savehist)
(require 'config-marginalia)
(require 'config-emacs)
(require 'config-vertico)
(require 'config-orderless)
(require 'config-company)
(require 'config-nix-mode)
(require 'config-magit)
(require 'config-avy)
(require 'config-org-roam)
(require 'config-org)
(require 'config-yas)
(require 'config-salt-mode)
(require 'config-eglot)
(require 'config-custom-fun)
(require 'config-embark)

;; init.el ends here
